name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      REPO_COOKER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
        deno-version: [2.x, rc, canary]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      id: node
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Setup Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      id: deno
      with:
        deno-version: ${{ matrix.deno-version }}
        cache: 'deno'    
    
    - run: |
        npm version
        npm ci
        npm run lint
        npm run checkdeps
        npm test
    - run: |
        deno version
        deno lint
        deno run --no-npm
